---
- hosts: webservers
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
        - python3-venv

    - name: Clone repository
      git:
        repo: "{{ repository_url }}"
        dest: "/opt/myapp"
        version: "main"

    - name: Install Python requirements
      pip:
        requirements: "/opt/myapp/requirements.txt"
        virtualenv: "/opt/myapp/venv"

    - name: Start application
      shell: |
        . /opt/myapp/venv/bin/activate
        nohup python /opt/myapp/app/main.py > /var/log/myapp.log 2>&1 &
      async: 45
      poll: 0
